# Site settings
title: Islam Essam Saeed | اسلام عصام
description: Cyber Security Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Islam Essam Saeed | اسلام عصام سعيد
user_description: I'm a Cyber Security Engineer from Egypt, always searching for the next challenge; no task is too scary nor too difficult. Lately Interested in how to analyze malware and network traffic and threat intelligence tools and techniques.
اسلام عصام سعيد 
user_title: Cyber Security Engineer 
email: islamessam459@gmail.com
twitter_username: Islam11Essam
github_username: Mal-X-Hunter
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "6333684402"

exclude: ['package.json', 'src' , 'node_modules']
