# Site settings
title: Islam Essam
description: Cyber Security Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Islam Essam
user_description:  I'm a Cyber Security Engineer from Egypt, always searching for the next challenge; no task is too scary nor too difficult. Lately Interested in how to analyze malware and network traffic
and threat intelligence tools and techniques.
user_title: Cyber Security Engineer 
email: islamessam459@gmail.com
twitter_username: Islam11Essam
github_username:  Cyber-Punisher
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
